/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activities */
        get: operations["read_activities_activities__get"];
        put?: never;
        /** Create Activity */
        post: operations["create_activity_activities__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activities/{activity_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity */
        get: operations["read_activity_activities__activity_id___get"];
        put?: never;
        post?: never;
        /** Delete Activity */
        delete: operations["delete_activity_activities__activity_id___delete"];
        options?: never;
        head?: never;
        /** Update Activity */
        patch: operations["update_activity_activities__activity_id___patch"];
        trace?: never;
    };
    "/activities/{activity_id}/zones/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity Zones */
        get: operations["read_activity_zones_activities__activity_id__zones__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Auth */
        post: operations["google_auth_auth_google__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/best/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Best Performances */
        get: operations["read_best_performances_best__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/best/power-profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Power Profile */
        get: operations["read_power_profile_best_power_profile__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fitness/ftp/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Fitness Ftp */
        get: operations["read_fitness_ftp_fitness_ftp__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fitness/scores/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Fitness Scores */
        get: operations["read_fitness_scores_fitness_scores__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/fitness/zones/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Fitness Zones */
        get: operations["read_fitness_zones_fitness_zones__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/heatmap/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Heatmap */
        get: operations["read_heatmap_heatmap__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Profile */
        get: operations["read_profile_profile__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Current User */
        get: operations["read_current_user_users_me__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Current User */
        patch: operations["update_current_user_users_me__patch"];
        trace?: never;
    };
    "/weeks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Weeks */
        get: operations["read_weeks_weeks__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityList */
        ActivityList: {
            /**
             * Activities
             * @default []
             */
            activities: (components["schemas"]["ActivityPublic"] | components["schemas"]["ActivityPublicWithoutTracepoints"])[];
            /**
             * @default {
             *       "page": 1,
             *       "per_page": 10,
             *       "total": 10
             *     }
             */
            pagination: components["schemas"]["Pagination"];
        };
        /** ActivityPublic */
        ActivityPublic: {
            /** Avg Cadence */
            avg_cadence?: number | null;
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /** Avg Power */
            avg_power?: number | null;
            /** Avg Speed */
            avg_speed?: number | null;
            /** Avg Temperature */
            avg_temperature?: number | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Delta Lat */
            delta_lat?: number | null;
            /** Delta Lon */
            delta_lon?: number | null;
            /** Description */
            description?: string | null;
            /** Device */
            device: string;
            /** Fit */
            fit: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Intensity Factor */
            intensity_factor?: number | null;
            /**
             * Laps
             * @default []
             */
            laps: components["schemas"]["Lap"][];
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Max Cadence */
            max_cadence?: number | null;
            /** Max Heart Rate */
            max_heart_rate?: number | null;
            /** Max Power */
            max_power?: number | null;
            /** Max Temperature */
            max_temperature?: number | null;
            /** Min Temperature */
            min_temperature?: number | null;
            /**
             * Notifications
             * @default []
             */
            notifications: components["schemas"]["NotificationPublic"][];
            /** Np Power */
            np_power?: number | null;
            /** Num Lengths */
            num_lengths?: number | null;
            /**
             * Performance Power
             * @default []
             */
            performance_power: components["schemas"]["PerformancePower"][];
            /**
             * Performances
             * @default []
             */
            performances: components["schemas"]["Performance"][];
            /** Pool Length */
            pool_length?: number | null;
            /** Race */
            race: boolean;
            /** Sport */
            sport: string;
            /** Start Time */
            start_time: number;
            /**
             * Status
             * @default created
             */
            status: string;
            /** Subdivision */
            subdivision?: string | null;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
            /** Total Ascent */
            total_ascent?: number | null;
            /** Total Calories */
            total_calories?: number | null;
            /** Total Distance */
            total_distance: number;
            /** Total Elapsed Time */
            total_elapsed_time: number;
            /** Total Timer Time */
            total_timer_time: number;
            /** Total Training Effect */
            total_training_effect?: number | null;
            /**
             * Tracepoints
             * @default []
             */
            tracepoints: components["schemas"]["Tracepoint"][];
            /** Training Stress Score */
            training_stress_score?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** User Id */
            user_id?: string | null;
        };
        /** ActivityPublicWithoutTracepoints */
        ActivityPublicWithoutTracepoints: {
            /** Avg Cadence */
            avg_cadence?: number | null;
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /** Avg Power */
            avg_power?: number | null;
            /** Avg Speed */
            avg_speed?: number | null;
            /** Avg Temperature */
            avg_temperature?: number | null;
            /** City */
            city?: string | null;
            /** Country */
            country?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Delta Lat */
            delta_lat?: number | null;
            /** Delta Lon */
            delta_lon?: number | null;
            /** Description */
            description?: string | null;
            /** Device */
            device: string;
            /** Fit */
            fit: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Intensity Factor */
            intensity_factor?: number | null;
            /**
             * Laps
             * @default []
             */
            laps: components["schemas"]["Lap"][];
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Max Cadence */
            max_cadence?: number | null;
            /** Max Heart Rate */
            max_heart_rate?: number | null;
            /** Max Power */
            max_power?: number | null;
            /** Max Temperature */
            max_temperature?: number | null;
            /** Min Temperature */
            min_temperature?: number | null;
            /**
             * Notification Count
             * @default 0
             */
            notification_count: number;
            /** Np Power */
            np_power?: number | null;
            /** Num Lengths */
            num_lengths?: number | null;
            /**
             * Performance Power
             * @default []
             */
            performance_power: components["schemas"]["PerformancePower"][];
            /**
             * Performances
             * @default []
             */
            performances: components["schemas"]["Performance"][];
            /** Pool Length */
            pool_length?: number | null;
            /** Race */
            race: boolean;
            /** Sport */
            sport: string;
            /** Start Time */
            start_time: number;
            /**
             * Status
             * @default created
             */
            status: string;
            /** Subdivision */
            subdivision?: string | null;
            /** Timestamp */
            timestamp: number;
            /** Title */
            title: string;
            /** Total Ascent */
            total_ascent?: number | null;
            /** Total Calories */
            total_calories?: number | null;
            /** Total Distance */
            total_distance: number;
            /** Total Elapsed Time */
            total_elapsed_time: number;
            /** Total Timer Time */
            total_timer_time: number;
            /** Total Training Effect */
            total_training_effect?: number | null;
            /** Training Stress Score */
            training_stress_score?: number | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /** User Id */
            user_id?: string | null;
        };
        /** ActivityUpdate */
        ActivityUpdate: {
            /** Race */
            race?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /** ActivityZoneHeartRatePublic */
        ActivityZoneHeartRatePublic: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Time In Zone */
            time_in_zone: number;
            zone: components["schemas"]["ZonePublic"];
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
        };
        /** ActivityZonePacePublic */
        ActivityZonePacePublic: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Time In Zone */
            time_in_zone: number;
            zone: components["schemas"]["ZonePublic"];
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
        };
        /** ActivityZonePowerPublic */
        ActivityZonePowerPublic: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Time In Zone */
            time_in_zone: number;
            zone: components["schemas"]["ZonePublic"];
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
        };
        /** ActivityZonesResponse */
        ActivityZonesResponse: {
            /** Heart Rate */
            heart_rate: components["schemas"]["ActivityZoneHeartRatePublic"][];
            /** Pace */
            pace: components["schemas"]["ActivityZonePacePublic"][];
            /** Power */
            power: components["schemas"]["ActivityZonePowerPublic"][];
        };
        /** BestPerformanceItem */
        BestPerformanceItem: {
            activity: components["schemas"]["ActivityPublicWithoutTracepoints"];
            /** Value */
            value: number;
        };
        /** BestPerformanceResponse */
        BestPerformanceResponse: {
            /** Parameter */
            parameter: string;
            /** Performances */
            performances: components["schemas"]["BestPerformanceItem"][];
            /** Sport */
            sport: string;
        };
        /** Body_create_activity_activities__post */
        Body_create_activity_activities__post: {
            /** Fit File */
            fit_file: string;
            /**
             * Race
             * @default false
             */
            race: boolean;
            /** Title */
            title: string;
        };
        /**
         * CyclingDistance
         * @enum {string}
         */
        CyclingDistance: "1" | "5" | "10" | "20" | "60" | "120" | "240";
        /** GoogleAuthResponse */
        GoogleAuthResponse: {
            token: components["schemas"]["Token"];
            user: components["schemas"]["UserPublic"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapPolyline */
        HeatmapPolyline: {
            /** Coordinates */
            coordinates: number[][];
            /** Sport */
            sport: string;
        };
        /** HeatmapPublic */
        HeatmapPublic: {
            /** Activity Count */
            activity_count: number;
            /** Point Count */
            point_count: number;
            /** Polylines */
            polylines: components["schemas"]["HeatmapPolyline"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Lap */
        Lap: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index */
            index: number;
            /** Max Heart Rate */
            max_heart_rate?: number | null;
            /** Max Speed */
            max_speed?: number | null;
            /** Start Time */
            start_time: number;
            /** Total Distance */
            total_distance: number;
            /** Total Elapsed Time */
            total_elapsed_time: number;
            /** Total Timer Time */
            total_timer_time: number;
        };
        /** NotificationPublic */
        NotificationPublic: {
            /** Achievement Year */
            achievement_year?: number | null;
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Distance */
            distance?: number | null;
            /** Duration */
            duration?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Message */
            message: string;
            /** Power */
            power?: number | null;
            /** Rank */
            rank?: number | null;
            /** Type */
            type: string;
        };
        /** Pagination */
        Pagination: {
            /**
             * Page
             * @default 1
             */
            page: number;
            /**
             * Per Page
             * @default 10
             */
            per_page: number;
            /**
             * Total
             * @default 10
             */
            total: number;
        };
        /** Performance */
        Performance: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Distance */
            distance: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Time */
            time?: string | null;
        };
        /** PerformancePower */
        PerformancePower: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Power */
            power: number;
            /**
             * Time
             * Format: duration
             */
            time: string;
        };
        /** PowerProfileResponse */
        PowerProfileResponse: {
            /** Available Years */
            available_years: number[];
            /** Labels */
            labels: string[];
            /** Overall */
            overall: number[];
            /** Years */
            years: {
                [key: string]: number[];
            };
        };
        /** Profile */
        Profile: {
            /**
             * Cycling N Activities
             * @default 0
             */
            cycling_n_activities: number;
            /**
             * Cycling Total Distance
             * @default 0
             */
            cycling_total_distance: number;
            /**
             * N Activities
             * @default 0
             */
            n_activities: number;
            /**
             * Run N Activities
             * @default 0
             */
            run_n_activities: number;
            /**
             * Run Total Distance
             * @default 0
             */
            run_total_distance: number;
            /**
             * Swimming N Activities
             * @default 0
             */
            swimming_n_activities: number;
            /**
             * Swimming Total Distance
             * @default 0
             */
            swimming_total_distance: number;
            /**
             * Years
             * @default []
             */
            years: components["schemas"]["YearsStatistics"][];
            /**
             * Zones
             * @default []
             */
            zones: components["schemas"]["ZonePublic"][];
        };
        /**
         * RunningDistance
         * @enum {string}
         */
        RunningDistance: "1" | "5" | "10" | "21.098" | "42.195";
        /**
         * Sport
         * @enum {string}
         */
        Sport: "running" | "cycling" | "swimming";
        /** Statistic */
        Statistic: {
            /**
             * N Activities
             * @default 0
             */
            n_activities: number;
            /** Sport */
            sport: string;
            /** Total Distance */
            total_distance?: number | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Token Type */
            token_type: string;
        };
        /** Tracepoint */
        Tracepoint: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Altitude */
            altitude?: number | null;
            /** Cadence */
            cadence?: number | null;
            /** Distance */
            distance: number;
            /** Heart Rate */
            heart_rate: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Power */
            power?: number | null;
            /** Speed */
            speed: number;
            /** Temperature */
            temperature?: number | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Google Id */
            google_id: string;
            /** Google Picture */
            google_picture?: string | null;
            /** Last Name */
            last_name: string;
        };
        /** UserPublic */
        UserPublic: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Cycling Enabled
             * @default true
             */
            cycling_enabled: boolean;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Google Id */
            google_id: string;
            /** Google Picture */
            google_picture?: string | null;
            /** Id */
            id: string;
            /** Last Name */
            last_name: string;
            /**
             * Map
             * @default leaflet
             */
            map: string;
            /**
             * Running Enabled
             * @default true
             */
            running_enabled: boolean;
            /**
             * Swimming Enabled
             * @default true
             */
            swimming_enabled: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Cycling Enabled */
            cycling_enabled?: boolean | null;
            /** Map */
            map?: string | null;
            /** Running Enabled */
            running_enabled?: boolean | null;
            /** Swimming Enabled */
            swimming_enabled?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeeklyActivitySummary */
        WeeklyActivitySummary: {
            /** Avg Heart Rate */
            avg_heart_rate?: number | null;
            /** Avg Power */
            avg_power?: number | null;
            /** Avg Speed */
            avg_speed?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Race */
            race: boolean;
            /** Sport */
            sport: string;
            /** Start Time */
            start_time: number;
            /** Title */
            title: string;
            /** Total Distance */
            total_distance: number;
            /** Total Timer Time */
            total_timer_time: number;
        };
        /** WeeklySummary */
        WeeklySummary: {
            /** Activities */
            activities: components["schemas"]["WeeklyActivitySummary"][];
            /** Sports Breakdown */
            sports_breakdown: {
                [key: string]: {
                    [key: string]: number;
                };
            };
            /** Total Activities */
            total_activities: number;
            /** Total Distance */
            total_distance: number;
            /** Total Time */
            total_time: number;
            /** Total Tss */
            total_tss: number;
            /** Week Number */
            week_number: number;
            /**
             * Week Start
             * Format: date-time
             */
            week_start: string;
            /** Year */
            year: number;
        };
        /** WeeksResponse */
        WeeksResponse: {
            /** Has More */
            has_more: boolean;
            /** Next Offset */
            next_offset: number;
            /** Weeks */
            weeks: components["schemas"]["WeeklySummary"][];
        };
        /** YearsStatistics */
        YearsStatistics: {
            /** Statistics */
            statistics: components["schemas"]["Statistic"][];
            /** Year */
            year: number;
        };
        /** ZonePublic */
        ZonePublic: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /** Index */
            index: number;
            /** Max Value */
            max_value: number;
            /** Type */
            type: string;
            /** User Id */
            user_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_activities_activities__get: {
        parameters: {
            query?: {
                map?: boolean;
                limit?: number;
                race?: boolean;
                sport?: string;
                min_distance?: number;
                max_distance?: number;
                page?: number;
                order?: string;
                order_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_activities__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_activity_activities__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_activities__activity_id___get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_activities__activity_id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_activity_activities__activity_id___patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_zones_activities__activity_id__zones__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityZonesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_auth_auth_google__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_best_performances_best__get: {
        parameters: {
            query: {
                sport: components["schemas"]["Sport"];
                distance?: components["schemas"]["CyclingDistance"] | null;
                time?: components["schemas"]["RunningDistance"] | null;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BestPerformanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_power_profile_best_power_profile__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PowerProfileResponse"];
                };
            };
        };
    };
    read_fitness_ftp_fitness_ftp__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_fitness_scores_fitness_scores__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_fitness_zones_fitness_zones__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_heatmap_heatmap__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapPublic"];
                };
            };
        };
    };
    read_profile_profile__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    read_current_user_users_me__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
    update_current_user_users_me__patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_weeks_weeks__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeeksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
