[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.71",
    "fastapi[standard]>=0.141.1",
    "psycopg2>=2.9.12",
    "pydantic>=2.13.4",
    "pyjwt>=2.13.0",
    "pyyaml>=6.0.2",
    "shapely>=2.1.2",
    "sqlmodel>=0.0.39",
    "typer>=0.27.1",
]

[dependency-groups]
dev = [
    "alembic>=1.19.1",
    "maturin>=1.13.3",
    "mypy>=2.3.0",
    "pydantic-settings>=2.15.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.0.0",
    "ruff>=0.16.3",
    "types-pyyaml>=6.0.12.20260724",
    "types-boto3>=1.43.71",
    "ty>=0.0.71",
    "hypothesis>=6.165.5",
    "types-shapely>=2.1.0.20260728",
]

[build-system]
requires = ["maturin>=1.13.3,<2.0"]
build-backend = "maturin"

[tool.ruff.lint]
ignore = ["DTZ"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.File"]

[tool.coverage.run]
relative_files = true

[tool.maturin]
features = ["pyo3/extension-module"]
python-source = "python"

[project.scripts]
cli = "api.cli:app"
